spring:
  data:
    mongodb:
      uri: mongodb+srv://ricardohsmello:**@cluster0.ols7ffa.mongodb.net/caixa
      database: caixa
      collection:
        financing: financing
        installments: installments
